name: MyAnnouncements
version: 1.2
author: Zee
main: net.craftmountain.myannouncements.MyAnnouncements
depend: [Vault]

commands:
  myannouncements:
    description: MyAnnouncements base command
    aliases: [myannouncement, mya, ma]

permissions:
  ma.*:
    description: Gives access to all MyAnnouncements commands
    default: false
    children:
      ma.base: true
      ma.admin: true
  ma.base:
    description: Gives access to MyAnnouncements base command
    default: true
  ma.admin:
    description: Gives access to all administrative commands
    default: op
